[slack]
webhook_url = "https://hooks.slack.com/services/xxxxx/yyyyy/zzzzz"
channel = "command"

[aws]
secret_access_key = "XXXXXXXXXX"
access_key_id = "XXXXXXXXXX"
region = "us-east-1"
queue_url = "https://sqs.us-east-1.amazonaws.com/0000000000/xxxxx"

[[directives]]
name = "uptime"
cmd = [
	["uname", "-a"],
	["uptime"],
]
output = true
