slack_webhook_url = "https://hooks.slack.com/services/xxxxx/yyyyy/zzzzz"

[aws]
secret_access_key = "XXXXXXXXXX"
access_key_id = "XXXXXXXXXX"
region = "us-east-1"
queue = "qqqqqqqqqq"

[[commands]]
name = "uptime"
memo = "execute uptime & uname"
programs = [
	["uname", "-a"],
	["uptime"],
]
output = true
